### PR TITLE
DEVC-18 : Added Sync Async and PDF changes

### PR DESCRIPTION
**Pull request by yogeshmpandey**
Added Review comments from Priyanka

- Sync Async Sample 
- Pdf changes

### CODE REVIEW

**Comment by nyurguhun** [comment]
@yogeshmpandey Please remove metadata from the jupyter notebooks by restarting the kernel + clearing the output and then saving it and committing here afterwards. Thanks!

**Comment by yogeshmpandey** [comment]
Hi @nyurguhun, metadata after testing the labs is removed from the labs by restarting the kernel + clearing the output. Can you please provide the .ipynb file name where you saw the metadata in the pushed files?

**Comment by nyurguhun** [comment]
> Hi @nyurguhun, metadata after testing the labs is removed from the labs by restarting the kernel + clearing the output. Can you please provide the .ipynb file name where you saw the metadata in the pushed files?

@yogeshmpandey https://github.com/intel-iot-devkit/iot-devcloud/pull/40/files#diff-04231f93b224c01285a351c548b3f6d4R37-R39

**Comment by yogeshmpandey** [comment]
> > Hi @nyurguhun, metadata after testing the labs is removed from the labs by restarting the kernel + clearing the output. Can you please provide the .ipynb file name where you saw the metadata in the pushed files?
> 
> @yogeshmpandey https://github.com/intel-iot-devkit/iot-devcloud/pull/40/files#diff-04231f93b224c01285a351c548b3f6d4R37-R39

Thanks @nyurguhun for that input. I have removed that metadata now.

**Comment by nyurguhun** [comment]
@yogeshmpandey Did you add the async example (one that shows all the layers with -pc flag) to hardware heterogeneity lab, per Priyanka's request?

**Pull request merged**
